### ISSUE TITLE
just want to inform you mlang still go though HOAS

### ISSUE THREAD

**Issue by molikto** [AndrasKovacs/normalization-bench#1]
it use bytecode generation to efficiently generate HOAS. before it use Scala compiler and Scala code generation which is hellishly slow. but in terms of generated code speed, it seems the generated code is not actually faster than compiling from Scala.

If what in your mind is generating records to JVM classes and functions to JVM functions, this is not what mlang is doing currently

**Comment by AndrasKovacs** [comment]
I edited the README.

Could you explain a bit more how your codegen works? Do you generate bytecode which is (roughly) the same as what you'd get through Scala?

**Comment by molikto** [comment]
Yes. the genereted code is instances of the `Value` ADT, and the Value ADT looks just like what you got in your Scala benchmarks. (except on master `app` is not a method, but `App` case of `Value`, because I need whnf, so it should be much slower than CBV, but changing to CBV should be relatively straightforward )
