### ISSUE TITLE
Suspicious average time for OCaml HOAS Nat 10M normalization

### ISSUE THREAD

**Issue by hirrolot** [AndrasKovacs/normalization-bench#10]
I have re-run the OCaml HOAS benchmark and obtained the following numbers:

<details>
<summary>Show the stats</summary>

```
Nat 5M conversion
Iterations: 5
true
true
true
true
true

Average time: 0.401441s
Nat 5M normalization
Iterations: 5
true
true
true
true
true

Average time: 2.850329s
Nat 10M conversion
Iterations: 5
true
true
true
true
true

Average time: 0.779622s
Nat 10M normalization
Iterations: 5
true
true
true
true
true

Average time: 10.962495s
Tree 2M conversion
Iterations: 5
true
true
true
true
true

Average time: 0.049158s
Tree 2M normalization
Iterations: 5
true
true
true
true
true

Average time: 0.281091s
Tree 4M conversion
Iterations: 5
true
true
true
true
true

Average time: 0.081503s
Tree 4M normalization
Iterations: 5
true
true
true
true
true

Average time: 0.548169s
Tree 8M conversion
Iterations: 5
true
true
true
true
true

Average time: 0.160363s
Tree 8M normalization
Iterations: 5
true
true
true
true
true

Average time: 1.153197s
```

</details>

The suspicious line is `Average time: 10.962495s`. From the `README.md` stats I see that it's 965 milliseconds on your machine, which is a huge difference.

I've compiled my code with `-O3` and my compiler version is 5.0.0 (build with Flambda).

What are your thoughts on this? Does this particular test really take 965 milliseconds on your machine?

**Comment by AndrasKovacs** [comment]
I've just reproduced this with ocamlopt 5.0.0, without flambda (there's no flambda for 5.* on opam and I haven't yet investigated how to get it). Sure it's weird. The README numbers were on Ocaml 4.1 so that's the most plausible source of regression.

**Comment by AndrasKovacs** [comment]
I tried with README options for OCAMLRUNPARAM. That solved the issue, but it looks excessive on Ocaml 5.0.0, because it gets me 3.1 GB RAM occupancy. Using `s=10000000` still takes 1.97 GB, and with that the Tree 2M conversion is 1.1 second, so it's still an outlier. Looks like some garbage collection shenanigans.

**Comment by AndrasKovacs** [comment]
Try to run it with `s=10000000` in OCAMLRUNPARAM, as in the README. That gets me 1.1s for that on ocamlopt-5.0.0 without flambda on my current laptop, not far from the old 965 ms.

**Comment by hirrolot** [comment]
Indeed -- with `OCAMLRUNPARAM` set to `s=10000000` it worked much faster. Probably an OCaml implementation peculiarity or something.
