### ISSUE TITLE
Have a try on GraalVM?

### ISSUE THREAD

**Issue by ice1000** [AndrasKovacs/normalization-bench#9]
I think for Scala, you could take a look at GraalVM. I heard they have very good devirtualization optimisation.

**Comment by ice1000** [comment]
Also various versions of HotSpot JVM may also differ

**Comment by AndrasKovacs** [comment]
Thanks for the suggestion. I added GraalVM Scala benchmark times. It's great on trees (the winner almost everywhere) but seems to have a performance issue with deep stacks.

**Comment by ice1000** [comment]
> Thanks for the suggestion. I added GraalVM Scala benchmark times. It's great on trees ((the winner almost everywhere) but seems to have a performance issue with deep stacks.

Thank you! That's very interesting. What do you think about the idea TCO-ed HOAS? Arend had got some interesting optimizations here but they don't have HOAS.

**Comment by AndrasKovacs** [comment]
Well, many functions are just not tail recursive. 

The GHC and OCaml HOAS versions both do TCO whenever possible, but they also can't TCO the `quote` function, and they still perform well.

IMO the solution is simply to allow large allocations using the stack discipline, without incurring unnecessary overhead. One could move the frames to a generic heap instead, but that only shifts deallocation work to GC, which is guaranteed to be more expensive than using stack discipline.

**Comment by glyh** [comment]
(You can also try Scala native
